apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: dns-access
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/description: >-
      Allows DNS access in the cluster     
spec:
  rules:
  - name: dns-access
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: NetworkPolicy
      name: dns-access
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          # select all pods in the namespace
          podSelector:
            matchLabels: {}
          policyTypes:
          - Egress
          egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  name: kube-system
            ports:
            - protocol: UDP
            port: 53
            - protocol: TCP
            port: 53
          - to:
            - ipBlock:
                cidr: 172.20.0.10/32
            ports:
            - protocol: UDP
              port: 53
            - protocol: TCP
              port: 53
