apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: rds-access
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/description: >-
      Allows access to specific RDS instance     
spec:
  rules:
  - name: rds-access
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: NetworkPolicy
      name: rds-access
      namespace: rds-test
      synchronize: true
      data:
        spec:
          # select all pods in the namespace
          podSelector:
            matchLabels:
              run: "pgsql-postgresql-client-1"
          policyTypes:
          - Egress
          egress:
          - to:
            - ipBlock
                cidr: 172.31.29.37/32    
